---
title: "Iterated Prisioner's Dilemma"
author: "Sérgio Rivero"
date: "`r Sys.time()`"
output:
  html_document:
    number_sections: TRUE
  pdf_document:
    number_sections: TRUE

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE, eval = TRUE)

### Generating the simulation Results
rm(list=ls())
```


```{r loadLibs}

### Getting the Libraries
library(tidyverse)

```


```{r setupDirs}

### Setting up the Directories
i  <-  "../runs"
o  <-  "../results"
```



```{r getFiles}

### Getting the files 
csv_files <- fs::dir_ls(i, regexp = "\\.csv$")

```



```{r generatingDF}

### Generating runs dataframe

runs_df  <- csv_files %>%
    map_dfr(read_csv)
runs_df_or  <-  runs_df
runs_df  <- runs_df[complete.cases(runs_df),]

runs_df$diff_payoffs  <- runs_df$my_payoff - runs_df$other_payoff


```

```{r}
sum_runs <- runs_df %>% group_by(scenario, step, strategy_name) %>% 
  summarise(payoff_mean = mean(my_payoff, na.rm = T),
            payoff_sum = sum(my_payoff, na.rm = T)
    )

sum_cooperation <- runs_df %>% group_by(scenario, step) %>%
  summarise(my_play_C = sum(ifelse(my_play == "C", 1,0), na.rm = T),
            my_play_D = sum(ifelse(my_play == "D", 1,0), na.rm = T),
            ot_play_C = sum(ifelse(other_play == "C", 1,0), na.rm = T),
            ot_play_D = sum(ifelse(other_play == "D", 1,0), na.rm = T),
            players = n()
) %>%
  mutate( cooperation = (my_play_C)/players,
          defection = (my_play_D)/players)


```




```{r}
sum_runs %>%  ggplot(aes(x=step, y = payoff_mean, color = strategy_name))  + geom_point(alpha=0.1) + geom_smooth()
```


```{r}
sum_runs %>%  ggplot(aes(x=strategy_name, y = payoff_mean, color = strategy_name)) + 
                geom_violin() + 
                geom_boxplot(width = 0.2) + 
                stat_summary(fun.y=mean, 
                             geom="point", 
                             shape=20, 
                             size=3, 
                             color="red")

```



```{r}
sum_cooperation %>%  ggplot(aes(x=step, y = cooperation)) + geom_point(alpha = 0.5) + geom_smooth()

```

